[project]
name = "algo-py"
version = "0.1.0"
description = "Learn algorithms with Python"
readme = "README.md"
authors = [
    { name = "Mystic" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
